import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { parseCsv } from "./lib/csv.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const today = new Date().toISOString().slice(0, 10);

const CPU_HEADERS = [
  "name", "brand", "year", "cores", "threads", "tier", "x3d",
  "fps1080p", "fps1440p", "fps4k", "fpsUltrawide", "low1Ratio",
  "source", "sampleCount", "lastVerified"
];

const GPU_HEADERS = [
  "name", "brand", "year", "vram", "tier", "segment", "rt",
  "fps1080p", "fps1440p", "fps4k", "fpsUltrawide", "low1Ratio",
  "source", "sampleCount", "lastVerified"
];

function num(v, field, row) {
  const n = Number(v);
  if (Number.isNaN(n)) throw new Error(`Invalid number for ${field} in ${row.name}: ${v}`);
  return n;
}

function bool(v) {
  return v === "true" || v === true;
}

function validateCpu(row) {
  for (const h of CPU_HEADERS) {
    if (row[h] === undefined || row[h] === "") throw new Error(`CPU missing ${h}: ${row.name}`);
  }
}

function validateGpu(row) {
  for (const h of GPU_HEADERS) {
    if (row[h] === undefined || row[h] === "") throw new Error(`GPU missing ${h}: ${row.name}`);
  }
}

function buildCpuObject(row) {
  validateCpu(row);
  const fps1080p = num(row.fps1080p, "fps1080p", row);
  const fps1440p = num(row.fps1440p, "fps1440p", row);
  const fps4k = num(row.fps4k, "fps4k", row);
  const fpsUltrawide = num(row.fpsUltrawide, "fpsUltrawide", row);
  return {
    name: row.name,
    brand: row.brand,
    year: num(row.year, "year", row),
    cores: num(row.cores, "cores", row),
    threads: num(row.threads, "threads", row),
    tier: row.tier,
    x3d: bool(row.x3d),
    gameFps: fps1080p,
    cpuFps: { "1080p": fps1080p, "1440p": fps1440p, "4k": fps4k, ultrawide: fpsUltrawide },
    low1Ratio: num(row.low1Ratio, "low1Ratio", row),
    source: row.source,
    sampleCount: num(row.sampleCount, "sampleCount", row),
    lastVerified: row.lastVerified
  };
}

function buildGpuObject(row) {
  validateGpu(row);
  return {
    name: row.name,
    brand: row.brand,
    year: num(row.year, "year", row),
    vram: num(row.vram, "vram", row),
    tier: row.tier,
    segment: row.segment || "desktop",
    rt: num(row.rt, "rt", row),
    fps: {
      "1080p": num(row.fps1080p, "fps1080p", row),
      "1440p": num(row.fps1440p, "fps1440p", row),
      "4k": num(row.fps4k, "fps4k", row),
      ultrawide: num(row.fpsUltrawide, "fpsUltrawide", row)
    },
    low1Ratio: num(row.low1Ratio, "low1Ratio", row),
    source: row.source,
    sampleCount: num(row.sampleCount, "sampleCount", row),
    lastVerified: row.lastVerified
  };
}

function serializeJs(varName, data) {
  const header = `// AUTO-GENERATED by scripts/build-data.mjs on ${today}. Do not edit directly.\n// Edit data/sources/*.csv and run npm run build:data\n`;
  return header + `window.${varName} = ${JSON.stringify(data, null, 2)};\n`;
}

function updateConfigDate() {
  const configPath = path.join(root, "data/config.js");
  let config = fs.readFileSync(configPath, "utf8");
  config = config.replace(/dataLastReviewed:\s*"[^"]+"/, `dataLastReviewed: "${today}"`);
  fs.writeFileSync(configPath, config);
}

function main() {
  const cpuCsv = fs.readFileSync(path.join(root, "data/sources/cpus.csv"), "utf8");
  const gpuCsv = fs.readFileSync(path.join(root, "data/sources/gpus.csv"), "utf8");
  const cpus = parseCsv(cpuCsv).map(buildCpuObject);
  const gpus = parseCsv(gpuCsv).map(buildGpuObject);

  const cpuNames = new Set();
  const gpuNames = new Set();
  cpus.forEach((c) => {
    if (cpuNames.has(c.name)) throw new Error(`Duplicate CPU: ${c.name}`);
    cpuNames.add(c.name);
  });
  gpus.forEach((g) => {
    if (gpuNames.has(g.name)) throw new Error(`Duplicate GPU: ${g.name}`);
    gpuNames.add(g.name);
  });

  fs.writeFileSync(path.join(root, "data/cpus.js"), serializeJs("CPU_DATA", cpus));
  fs.writeFileSync(path.join(root, "data/gpus.js"), serializeJs("GPU_DATA", gpus));
  updateConfigDate();
  console.log(`Built ${cpus.length} CPUs and ${gpus.length} GPUs. dataLastReviewed=${today}`);
}

main();
